import { existsSync, statSync } from 'node:fs';
import { describe, expect, it } from 'vitest';

const REQUIRED_ASSETS = [
  'assets/tile/hell.png',
  'assets/tile/snow.png',
  'public/assets/tile/hell.png',
  'public/assets/tile/snow.png',
  'assets/icon/skill-magic-arrow.svg',
  'assets/icon/skill-multiple-arrow.svg',
  'assets/icon/skill-frost-arrow.svg',
  'assets/icon/skill-ice-arrow.svg',
  'assets/icon/skill-exploding-arrow.svg',
  'public/assets/icon/skill-magic-arrow.svg',
  'public/assets/icon/skill-multiple-arrow.svg',
  'public/assets/icon/skill-frost-arrow.svg',
  'public/assets/icon/skill-ice-arrow.svg',
  'public/assets/icon/skill-exploding-arrow.svg',
  'assets/icon/skill-magic-arrow.png',
  'assets/icon/skill-multiple-arrow.png',
  'assets/icon/skill-frost-arrow.png',
  'public/assets/icon/skill-magic-arrow.png',
  'public/assets/icon/skill-multiple-arrow.png',
  'public/assets/icon/skill-frost-arrow.png',
  'assets/char/amazon.png',
  'assets/char/barbarian.png',
  'assets/char/sorceress.png',
  'public/assets/char/amazon.png',
  'public/assets/char/barbarian.png',
  'public/assets/char/sorceress.png',
  'assets/prop/campfire.png',
  'assets/prop/exit_gate.png',
  'assets/prop/blacksmith_anvil.png',
  'public/assets/prop/campfire.png',
  'public/assets/prop/exit_gate.png',
  'public/assets/prop/blacksmith_anvil.png',
  'assets/mon/mephisto.png',
  'assets/mon/diablo.png',
  'assets/mon/baal.png',
  'assets/mon/fallen.png',
  'assets/mon/zombie.png',
  'assets/mon/skeleton.png',
  'assets/mon/shaman.png',
  'assets/mon/archer.png',
  'assets/mon/brute.png',
  'public/assets/mon/mephisto.png',
  'public/assets/mon/diablo.png',
  'public/assets/mon/baal.png',
  'public/assets/mon/fallen.png',
  'public/assets/mon/zombie.png',
  'public/assets/mon/skeleton.png',
  'public/assets/mon/shaman.png',
  'public/assets/mon/archer.png',
  'public/assets/mon/brute.png',
  'assets/npc/akara.png',
  'assets/npc/kashya.png',
  'assets/npc/charsi.png',
  'assets/npc/gheed.png',
  'assets/npc/warriv.png',
  'assets/npc/cain.png',
  'public/assets/npc/akara.png',
  'public/assets/npc/kashya.png',
  'public/assets/npc/charsi.png',
  'public/assets/npc/gheed.png',
  'public/assets/npc/warriv.png',
  'public/assets/npc/cain.png',
];

describe('V4 visual asset pack', () => {
  it('keeps key V4 assets available for dev and GitHub Pages', () => {
    for (const file of REQUIRED_ASSETS) {
      expect(existsSync(file), `${file} should exist`).toBe(true);
      expect(statSync(file).size, `${file} should not be empty`).toBeGreaterThan(512);
    }
  });
});
